AllCops:
  Exclude:
    - 'config/puma.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  NewCops: enable

Layout/HashAlignment: # Helps make hashes more readable
  EnforcedHashRocketStyle: table

Layout/LineLength: # Screens are wide enough these days
  Max: 150
  Exclude:
    - 'spec/**/*'
    - 'Gemfile'

Metrics/AbcSize: # Reduces the number of disable statements I need to add for perfectly reasonable code
  CountRepeatedAttributes: false
  Max: 20

Metrics/BlockLength: # Don't worry about long blocks in tests
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/MethodLength: # Longer methods are sometimes necessary
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']
  Exclude:
    - 'spec/**/*'

Naming/AccessorMethodName: # Sometimes get is a useful prefix
  Enabled: false

Style/Documentation: # Not all classes need a big comment at the top
  Enabled: false

Style/FrozenStringLiteralComment: # Life is too short to be adding a magic comment to every document
  Enabled: false
  
Style/TrailingCommaInArrayLiteral: # Trailing commas mean cleaner diffs
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral: # Trailing commas mean cleaner diffs
  EnforcedStyleForMultiline: comma

Style/StringLiterals: # Life is too short to argue about single vs double quotes
  Enabled: false