name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop

  security:
    name: Dependency security audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Security audit gems
        run: bundle exec bundler-audit --update

      - name: Run npm audit
        run: npm audit --audit-level=moderate

  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:8-alpine@sha256:8096655e437712b07503796fb64d81359256cfcff0ab29d95a7da72863786efb
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install node modules
        run: npm install

      - name: Run tests
        env:
          REDIS_URL: redis://localhost:6379/0
        run: bundle exec rspec
